env:
  browser: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
globals:
  wx: true
  App: true
  getApp: true
  x: true
  res: true
  Page: true
  getCurrentPages: true
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - off
    - windows
  semi:
    - warn
    - always
  "no-use-before-define":
    - error
    - { functions: false, classes: true }
  "no-console": off
  "no-unused-vars":
    - error
    - { vars: all, args: none, ignoreRestSiblings: false}